steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', '--build-arg', 'TERRAGRUNT_VERSION=v0.38.7', '.']
    dir: 'terragrunt'

images: ['${_IMAGE}']

substitutions:
  _IMAGE: 'europe-west4-docker.pkg.dev/${PROJECT_ID}/docker/terragrunt:${TAG_NAME:-${SHORT_SHA}}'
