steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', '.']

images: ['${_IMAGE}']

substitutions:
  _IMAGE: 'europe-west4-docker.pkg.dev/${PROJECT_ID}/docker/terragrunt:${TAG_NAME:-${SHORT_SHA}}'
